name: Build Qt 5.15

on:
  workflow_dispatch:

jobs:
  Build_x64:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Qt sources
        run: .\download_sources.cmd repack_sources
      
      - name: Upload patched Qt sources
        uses: actions/upload-artifact@v4
        with:
          name: Qt 5.15.13 patched src
          path: |
            src_archive/*
          compression-level: 9
          retention-days: 5

      - name: Install Qt jom
        run: .\install_jom.cmd
      
      - name: Build Qt x64
        run: .\build_sources.cmd x64
      
      - name: Upload built Qt
        uses: actions/upload-artifact@v4
        with:
          name: Qt 5.15.13 x64
          path: |
            archive/*
          compression-level: 9

  Build_x86:
    runs-on: windows-2019
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Qt sources
        run: .\download_sources.cmd
        
      - name: Install Qt jom
        run: .\install_jom.cmd
              
      - name: Build Qt x64
        run: .\build_sources.cmd Win32
              
      - name: Upload built Qt
        uses: actions/upload-artifact@v4
        with:
          name: Qt 5.15.13 x86
          path: |
            archive/*
          compression-level: 9